---
- hosts: webservers 
  become: True
  tasks:
    - name: Update apt
      become: True
      apt:
         update_cache: yes
    - name: Task -2 Install Java using Ansible
      become: True
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
           - openjdk-11-jdk
    - name: Install Maven
      raw: sudo apt install maven -y
    - name: Copy file with owner and permissions
      copy:
        src:  /var/lib/jenkins/workspace/petclinic2_main/target/spring-petclinic-2.7.0-SNAPSHOT.jar
        dest: /home/ubuntu/app/
        owner: root
        group: root
        mode: '0644'
    - name : Kill processes on port 8080
      shell:
        cmd: sudo fuser -k 8080/tcp > /dev/nul
      ignore_errors: true
    - name: Deploy jar file
      raw: java -Dserver.port=8080 -jar /home/ubuntu/app/*.jar
...
