---
- hosts: webservers 
  become: True
  tasks:
    - name: Install wget
      apt: pkg=wget
    - name: Install jre
      raw: sudo apt install default-jre -y
    - name: Install JDK
      raw: sudo apt install openjdk-11-jdk -y
    - name: Install Maven
      raw: sudo apt install maven -y
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src:  target/* 
        dest: /home/ubuntu/app/
        owner: root
        group: root
        mode: '0644'
    - name : Kill processes on port 8080
      raw: kill -9 $(sudo lsof -t -i:8080)
    - name: Deploy jar file
      raw: java -Dserver.port=8080 -jar /home/ubuntu/app/*.jar
...
